### ISSUE TITLE
ggpairs plot

### ISSUE THREAD

**Issue by ap1987-ap** [munoztd0/DAP_2021#16]
Hi David

I have an issue with ggpairs. 
I have 3 groups with different scores in the UPDRS_Total. HC (control group) here is missing, because they werent tested. Now it recodes the colours for the other two groups. How can i change that back to "normal".
I used this code:

ggpairs(df, aes(color=Group, alpha=0.5), lower=list(combo=wrap("facethist", binwidth=10.0)))

Thanks 
Anja

<img width="672" alt="ggpairs problem" src="https://user-images.githubusercontent.com/65404887/147083536-5957e65b-1f91-492b-9a6e-86d890151dca.png">

**Comment by ap1987-ap** [comment]
Hi, me again.

I changed my variables a bit, so it doesnt matter anyway.
But thank you ;-)

**Comment by munoztd0** [comment]
Well let me know if you need anything, but for the record you can explicitly assigne color value like this : 
```
your_plot(blablaba) + 
scale_fill_manual(values=c("control"= "blue", "patient"=  "red")) +
scale_color_manual(values=c("control"= "blue", "patient"=  "red")) +
```
just change "control" and "patient" by the name of your factor levels.

**Comment by ap1987-ap** [comment]
Ok, thank you.On 22 Dec 2021 13:59, David Muñoz Tord ***@***.***> wrote:
Well let me know if you need anything, but for the record you can explicitly assigne color value like this :
your_plot(blablaba) + 
scale_fill_manual(values=c("control"= "blue", "patient"=  "red")) +
scale_color_manual(values=c("control"= "blue", "patient"=  "red")) +

just change "control" and "patient" by the name of your factor levels.

**Comment by ap1987-ap** [comment]
I have another qeustion. What exactly do you code under pre-processing? When I look at your dap sample, it seems that you already analyze the data.
Under pre-processing i understand the cleaning of data, removement of outlierts etc.

Thanks

**Comment by munoztd0** [comment]
Pre processing is just everything that is before to model your data, it could be visual check, frequency tables, ... And cleaning data.
